### ISSUE TITLE
The version of plugins in DMM bundle does not change when bundle is downgraded

### ISSUE THREAD

**Issue by alnlarsen** [opentap/opentap#1159]
1. install DMM bundle v2.1.0
2. Downgrade DMM bundle to 2.0.3

Prior to 9.19, this would downgrade all the members of DMM, but now the image fails to install:

```
Could not resolve DMM v2.0.3
Image configuration:
  DMM: 2.0.3
  DMM API: ^2.1.3+26062d00
  DMM Instruments: ^2.1.3+26062d00
  DMM Test Steps: ^2.1.3+26062d00
  OpenTAP: ^9.23.2-beta.5+40fdd208
```

**Comment by Denrask** [comment]
We decide to push this to 9.23, as the consequences can introduce many new bugs in edge cases. This needs to be thought of really thoroughly.

**Comment by rmadsen-ks** [comment]
Maybe instead of the old behavior we should add a message to manually remove the current bundle and then install the new onel.

There is a question about what to do with the installed dependencies. When uninstalling a bundle it should ask which of the dependencies also to remove.  Once that is resolved the other version can be installed.

**Comment by bogdan-achim** [comment]
Verified in OpenTAP v9.24.0-beta.33

![image](https://github.com/opentap/opentap/assets/118886454/0f379805-2ca4-4506-b32a-bc60be8a52db)
