### ISSUE TITLE
Mixin Number type cannot be assign as an Output to a Log Message field from Log Output test step

### ISSUE THREAD

**Issue by Razvan-Muresan** [opentap/opentap#1394]
**Describe the bug**

Having a Mixin (Number type) with Output Option selected, I cannot assign that output into a Log Message field from a Log Output test step. If the Mixin is Text type the assign output option works

**Environment (please complete the following information):**

 - OS: e.g. Windows 10
 - OpenTAP Version 9.23

**To Reproduce**

1. Add a Delay Step and a Log Output Step
2. On Time Delay add a new Mixin (Type: Number / Options: Output)
3. On the Log Message from Log Output step try to assign the output to created mixin

**Actual behavior**
Log Message Output cannot be assign to a Number output mixin

![Uploading mixin output.gif…]()

**Comment by rmadsen-ks** [comment]
This is intentional You cannot assign a number to a text value. You can assign it using an expression, but it cannot be trivially assigned.

There is a feature request for this: #1368, but the question remains if a number can be assigned to a string. At least for decimal numbers that might not be trivial.

**Comment by rmadsen-ks** [comment]
@Razvan-Muresan, please reopen this if you think I misunderstood.
