### ISSUE TITLE
Test Plan Editor: "If" parameter from "If Verdict" step is cleared after parent step is moved as child of another step

### ISSUE THREAD

**Issue by bogdan-achim** [opentap/opentap#1456]
**Environment**
KS8400 9.22
KS8500 DEV 1.15

**Describe the bug**
"If" parameter from "If Verdict" step is cleared after parent step is moved as child of another step

**To Reproduce**

Add a Parallel test step
Add a Repeat test step
Add a Dialog step as a child of Repeat
Add an If Verdict step as a child of Repeat
Set "If" parameter to "Verdict from Dialog"
Move Repeat step as a child of Parallel

**Actual behavior**
The "If" parameter of "If Verdict" is cleared

**Screenshots**
![if_verdict_step_if_parameter_is_empty_after_adding_parent_step_as_child_to_another_step](https://github.com/opentap/opentap/assets/118886454/f0c7aac1-0748-4ed4-9fcc-83a0998838ca)

**Comment by alnlarsen** [comment]
I can reproduce the problem. I have created a unit test showing it here: https://github.com/opentap/opentap/pull/1495

From the test it is pretty clear what happens. The input to `IfVerdict` is cleared because the step was (temporarily) removed from the test plan. This is by design since we don't want inputs to point to invalid steps, but clearly we need a way to allow moving a step while preserving the settings.
