### ISSUE TITLE
Supporting relative paths

### ISSUE THREAD

**Issue by mattia-lecci** [opentap/opentap#1499]
**Describe the bug**

It may be more of a feature request than a bug report.
When using, e.g., `OpenTap.Plugins.BasicSteps.TestPlanReference` two counterintuitive things happen:
* When using KS8400 and selecting a tap plan from the local storage, a relative path is stored, e.g., `..\..\..\Users\<user>\Downloads\test1.TapPlan`
* The path is not relative to test plan, but apparently to the tap/Keysight Test Automation folder

**Environment (please complete the following information):**

 - OS: Windows 10
 - OpenTAP Version: OpenTAP Command Line Interface 9.23.2+5a906a86 / Keysight Test Automation 9.23.0+a3027bf1 (64-bit) official release

**To Reproduce**

1. Create test1.TapPlan in, e.g., `%userprofile%/Downloads`
    1. Add a single `OpenTap.Plugins.BasicSteps.LogStep` logging a simple string, e.g., `Hello world!`
1. Create test2.TapPlan in the same folder as test1.TapPlan
    1. Add a single `OpenTap.Plugins.BasicSteps.TestPlanReference` loading test1.TapPlan

**Actual behavior**

test2.TapPlan:
```xml
<?xml version="1.0" encoding="utf-8"?>
<TestPlan type="OpenTap.TestPlan">
  <Steps>
    <TestStep type="ref@OpenTap.Plugins.BasicSteps.TestPlanReference" Id="544186e7-b280-4cc8-acd6-7984fed8a212">
      <Filepath>..\..\..\Users\<user>\Downloads\test1.TapPlan</Filepath>
      <Hash>169F261FD0E313A7</Hash>
      <StepMapping />
      <Name Metadata="Step Name">Test Plan Reference</Name>
    </TestStep>
  </Steps>
  <Package.Dependencies>
    <Package Name="OpenTAP" Version="^9.23.2+5a906a86" />
  </Package.Dependencies>
</TestPlan>
```

**Expected behavior**

If relative paths are used, i would expect it to be relative to the TapPlan, not the Keysight Test Automatio/tap executable.
Otherwise, absolute paths should be used instead, i.e., `C:\Users\<user>\Downloads\test1.TapPlan`.

**Additional context**

**_Relative paths would be extremely convenient_** when creating a complex test plan, involving multiple sub-routines separated into different TapPlan files.
Given the complexity, it is often easier to work on such test plan on a personal computer, then move it to the actual testbed, or exchange it with a colleague to work on it in parallel (e.g., via git mirroring).
When this happens, though, all paths need to be changed according to the new machine.

**Comment by alnlarsen** [comment]
Hi @mattia-lecci 

File paths are usually `MacroStrings`. `MacroString` supports the `<TestPlanDir>` macro. If you want to specify a path that is relative to the test plan, you can specify the path as `<TestPlanDir>\test1.TapPlan`

The reason why a relative path from the installation directory is precisely because of the problem you mentioned. The same files will usually not be available on different machines. The only thing we can be certain of in such a scenario is that both machines contain a TAP installation. 

If someone creates a test plan that depends on other test plans, we would usually recommend bundling them in packages so they can:

1. Be registered as proper test plan dependencies, and 
2. we can ensure that they are in the proper, relative location.

Test Plans that are installed through a package will also show up as test steps in KS8400, though under the hood those steps are just `Test Plan Reference` steps. 

I hope this explanation makes sense, and that my proposed workaround works for you.

**Comment by mattia-lecci** [comment]
Thank you @alnlarsen , this solved my issues.
I also found `<TestPlanDir>` mentioned in the "How To" guide in KS8400 (Using Tags and Variables in File Names) and the [opentap doc](https://doc.opentap.io/Developer%20Guide/Appendix%20A/?#test-steps) (Appendix A: Macro Strings).

This assumes knowing a lot about the software already, i would suggest to associate it with "relative", "relative path", "working directory", etc. in the documentation.
In this way, an inexperienced opentap user (like myself :) ) could find it immediately!
