### ISSUE TITLE
Run Program: Test Plan cannot be stopped while Firefox is open

### ISSUE THREAD

**Issue by bogdan-achim** [opentap/opentap#1604]
**Environment**
KS8400 9.24.0-rc.2

**Describe the bug**
Test Plan cannot be stopped while Firefox is open

**To Reproduce**

1. Add a Run Program step
2. Set `firefox.exe` as application
3. Run the test plan
4. Wait for Firefox to be opened
5. Switch to KS8400
6. Press Stop
7. Actual behavior
8. The test plan cannot be stopped

**Additional notes**
This issue also occurs on older version of KS8400

**Screenshots**
![run_program_testplan_cannot_be_stopped](https://github.com/opentap/opentap/assets/118886454/f3db181f-6f3d-4851-98b5-b42754646348)

**Comment by alnlarsen** [comment]
In general, it's impossible to control a child process unless it cooperates. In the case of Firefox, it is spawning a child process that spawns a new window. So the initial process has actually exited, but because it forwarded its output / error pipes to the child process, they will never close, which causes issues in this case.

I think the best we can do in such scenarios it to allow aborting the test plan, and accept that the child process hangs instead of closing.

**Comment by sebastian-pop** [comment]
The test plan can now be aborted
