### ISSUE TITLE
Handle bad Visa configurations

### ISSUE THREAD

**Issue by bdirenzo-keysight** [opentap/opentap#1678]
Some users have noticed that some visas (tek and others) can cause issues with Visa Discovery (seen when adding a new instrument to a bench. 

We should look at ways to handle this better:
1. Try discovery and timeout, and allow for manual entry
2. Skip discovery and allow for manual entry
3. ?

**Comment by rmadsen-ks** [comment]
I think we at least need a manual override. It could just be an environment variable.  e.g OPENTAP_NO_VISA_DISCOVERY="true"

I have also seen the Visa DLL / resource manager causing unrecoverable segmentation faults.

I could imagine that when this happens you are no even going to be able to open a connection to the instrument, since its just completely broken, but at least it would provide us with a way around the problem.

**Comment by rmadsen-ks** [comment]
lets have a CLI action call "tap visa-discovery"  thats hidden, which outputs all available instruments in std out.

**Comment by rmadsen-ks** [comment]
Related: https://github.com/opentap/opentap/commit/8fd49cbac30ba07f26e8a5f89bb4a099bcae49eb
