### ISSUE TITLE
ci.yml: on pull_request increases build costs by a factor of 2.

### ISSUE THREAD

**Issue by rmadsen-ks** [opentap/opentap#556]
It seems that pushes now causes all build jobs to be run twice, causing an increased build cost.

**Comment by rmadsen-ks** [comment]
@g-galante, I think we will have to revert your otherwise fine change. Alternatively, we can try to limit most of the jobs being run on pull_requests. Do you have any idea?

**Comment by g-galante** [comment]
@rmadsen-ks It's a problem that seems to happen only for users with write access to the repository who push to branches for which a pull request is already open.

In your case, according to the `CI` workflow execution timeline for branch [`buildIssueFix`](https://github.com/opentap/opentap/actions/workflows/ci.yml?query=branch%3AbuildIssueFix), it is clear that the double workflow execution started only after workflow run `CI #880`, which was triggered by opening PR https://github.com/opentap/opentap/pull/554. After that, each `push` event on branch `buildIssueFix` also triggered a [`pull_request synchronize`](https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#pull_request) event, since it updated the branch `HEAD`,  until run `CI # 886`, which includes the proposed fix.

I fear it won't be easy to find a workflow configuration working equally well for users with write access to the repository directly pushing to its branches, and for users with read-only access submitting pull requests from (public) forks.

I'm also not sure that the change you merged yesterday will do what you want. I guess that, in this case, users with write access to the repository directly pushing to its branches will trigger a workflow run on a branch only after submitting a pull request on it, and after (pushing) its merge on `main` or `release9x`.

A similar behavior will hold for users with read-only repository access when they work on their forks: no workflow run will be triggered in the forked repository for pushes to the fork, unless they are on branches `main` or `release9x`, e.g., after a merge on such branches. Workflow runs will be triggered in the main `opentap/opentap` repository after the submission of a pull request, and after the head branch included in submitted pull request is updated (by a push to the fork).

**Comment by rmadsen-ks** [comment]
I think I have noticed that "on pull_requests", actually triggers on each push that affects the pull request. So I think the new workflow should work for every push to a branch that has a pull request. 

Anyway, we'll see..
