### ISSUE TITLE
Add generic CLI argument to name session log

### ISSUE THREAD

**Issue by AsgerIversen** [opentap/opentap#69]
Originally filed May 17 2021 by Alexander Nørskov Larsen on [GitLab](https://gitlab.com/OpenTAP/opentap/-/issues/657)

It would be nice to have an option to explicitly name the session log from a specific opentap cli action in some cases, such as CI pipelines

`tap run MyTestPlan --session-log "/path/to/log.txt"`

**Comment by g-galante** [comment]
@AsgerIversen implemented this in commit 4dd2f869741af7b239fdc404dacc60926bdad1c0 adding the `--log` option instead of `--session-log`.

This caused a clash with `tap sdk gitversion --log n`, solved redefining the latter as `tap sdk gitversion --gitlog n`: [GitLab issue OpenTAP/opentap#753](https://gitlab.com/OpenTAP/opentap/-/issues/753), merged with commit 46a11e15673076c962affc628bf76f0231b8f595.

Such a change was later (partially) reverted with [GitLab merge request OpenTAP/opentap!1004](https://gitlab.com/OpenTAP/opentap/-/merge_requests/1004#note_700821174) commit 2530e030098ad3af4a497f1a1aa5a6477f52fc75.
Indeed, the current command-help output still shows a stray reference to the no-longer-existing `--gitlog` option in the description of `--replace`:
```
$ tap sdk gitversion -h
Usage: gitversion [-h] [-v] [-c] [-q] [--log <arg>] [--replace <arg>] [--fields <arg>] [--dir <arg>] [<ref>]
  -h, --help      Write help information.
  -v, --verbose   Show verbose/debug-level log messages.
  -c, --color     Color messages according to their severity.
  -q, --quiet     Quiet console logging.
  --log           Print the git log for the last <arg> commits including their semantic version number.
  --replace       Replace all occurrences of $(GitVersion) in the specified file
                  with the calculated semantic version number. It cannot be used with --gitlog.
  --fields        Number of version fields to print/replace. The fields are: major, minor, patch,
                  pre-release, and build metadata. E.g., --fields=2 results in a version number
                  containing only the major and minor field. The default is 5 (all fields).
  --dir           Directory containing the git repository to calculate the version number from.
```
and no opportunity is provided to rename the session log.

Right now, the less-breaking change seems to restore `tap sdk gitversion --gitlog n` as it was accepted in the original [GitLab issue OpenTAP/opentap#753](https://gitlab.com/OpenTAP/opentap/-/issues/753) and related [GitLab merge request OpenTAP/opentap!980](https://gitlab.com/OpenTAP/opentap/-/merge_requests/980).

This would allow to have a `--log` common command-line option to rename session logs for each CLI action natively provided by OpenTAP as required by this issue.

Renaming the `--log` common command-line option to `--session-log` would make the trick as well, but it's very likely much more braking, since such a change was committed more than one year ago, on Jan 7, 2021 (4dd2f869741af7b239fdc404dacc60926bdad1c0).

I'm submitting a pull request since we need it in any case: 
- either to implement the solution I'm advocating for, 
- or to rename the `--log` common command-line option to `--session-log`,
- or to fix `tap sdk gitversion -h`.
