### ISSUE TITLE
Running the command to install with a specific --architecture will not return a warning for incompatibility

### ISSUE THREAD

**Issue by apantir** [opentap/opentap#818]
**Describe the bug**

Using this command on macOS: **./tap package install "Example Plugin" --arhitecture x86** on a x64 device will not return any warning of incompatibility and install directly the x64 version

**Environment (please complete the following information):**

 - OS: macOS 12.8
 - OpenTAP Version 9.19.0-beta.54

**To Reproduce**

1. Run this command in Terminal **./tap package install "Example Plugin" --arhitecture x86** on a x64 machine

2.  Check if there is a warning message

**Actual behavior**

Using this command on macOS: **./tap package install "Example Plugin" --arhitecture x86** on a x64 device will not return any warning of incompatibility and install directly the x64 version

**Expected behavior**

Trying to install a x86 package on a x64 machine needs to have a warning message and after install de compatible version

**Comment by rmadsen-ks** [comment]
@apantir, can you should what it printed instead?

**Comment by sebastian-pop** [comment]
@rmadsen-ks this is reproduced on windows as well. Log: 
[SessionLog.2022-09-14.14-06-54.txt](https://github.com/opentap/opentap/files/9583055/SessionLog.2022-09-14.14-06-54.txt)

![image](https://user-images.githubusercontent.com/97734470/190615481-4a6cb5c3-d028-4e47-9dfb-b13413c377dd.png)

A better example of this issue is using "Editor CE" which has separate versions for x64 and x86. Tested on Windows 10 x64.  

![image](https://user-images.githubusercontent.com/97734470/190616718-01266d94-48c0-4064-a281-8fb62c517927.png)

**Comment by sebastian-pop** [comment]
Same issue with `--os`

Can be tested on Windows with `tap package install "Editor X" --version 1.4.0 --os Linux -r https://packages.opentap.keysight.com -r http://packages.opentap.io` it will install the Windows version with no message

Running the same command with `--force` will show a message and install the Linux version 

![image](https://user-images.githubusercontent.com/97734470/190618194-cc724492-7cdd-4756-b2b9-7a18cd60a64e.png)

So this issue is basically: User is asking for an incompatible package: OpenTAP installs a compatible one without any message

**Comment by jfaaborg** [comment]
We will need to inform the user that the requested os or architecture is not compatible, before we auto resolve.

**Comment by sebastian-pop** [comment]
Fixed. Verified on 9.19.0-rc.3

![image](https://user-images.githubusercontent.com/97734470/190645801-459a798c-7ba9-4b87-9024-d49ae1f3a5dc.png)
