### ISSUE TITLE
Dont allow parameterizing a swept property

### ISSUE THREAD

**Issue by rmadsen-ks** [opentap/opentap#856]
Currently it is allowed to parameterize a swept parameter. This gives some confusion since the state of the parameterized property is read-only.

This simplest solution is to disable to parameterize functionality when a property is swept.

![image](https://user-images.githubusercontent.com/24250062/193556802-25b8d169-780d-4926-ba5a-f82733f57d84.png)

**Comment by bdirenzo-keysight** [comment]
@rmadsen-ks doesn't this conflict with what we are trying to do here? We have had specific requests to enable this. Agree it is confusing now since it is allowed, but doesn't work, but I think we should go in the direction of making it work rather than preventing it:
https://github.com/opentap/opentap/issues/786

**Comment by rmadsen-ks** [comment]
@bdirenzo-keysight, no, this is a bit different, but they are somewhat related.

 If you look at the screen shot, I have tried to express the problem of re-parameterizing the swept-over property further, not the sweep values. For examples, we are not blocking the user from parameterizing Start and Stop, which are values more analogous to "Sweep Values".
