### ISSUE TITLE
tap package install does not always show available updates

### ISSUE THREAD

**Issue by MikkoAla-Kojola** [opentap/opentap#871]
I find it convinient when updating OpenTAP packages, tap.exe tells me which other packages have an update available. 
But list of updates is not always printed into console. Not sure if that is a wanted feature but today I updated quite a few packages and did not notice any pattern on when other updates are listed and when not.

In screenshot updates are shown on first but not on the second install command.

![image](https://user-images.githubusercontent.com/101178944/194610344-498b5ed8-70f9-4735-bc94-63fa1a3eb247.png)

**Comment by rmadsen-ks** [comment]
When starting, it waits for around 3 seconds before doing the update check. This is to avoid slowing down short lived processes by doing the check (It can also be disabled altogether by setting OPENTAP_NO_UPDATE_CHECK). 

It also does not wait for the update check to complete before the application closes.

So in your case, since the command took 4 seconds, If for some reason the check itself takes 1 second or more, it might not complete before the application shuts down again.

The hidden (`Browsable(false)`) command `tap package check-updates` can be used to do an active update check.

**Comment by MikkoAla-Kojola** [comment]
Giulio: Good point on "possibly no updates available". But I think Timing analyzer and Result Viewer should still be available after installing Developer's System.

**Comment by MikkoAla-Kojola** [comment]
Giulio: I stand corrected. You are absolutely right, the reason why there is no list of available updates after updating Developer's System is that Visual Studio SDK, Timing Analyzer and Results Viewer where updated by Developer's System.

**Comment by alnlarsen** [comment]
Okay let's close this issue
