### ISSUE TITLE
Windows 7: Package Manager cannot use default repository https://packages.opentap.io

### ISSUE THREAD

**Issue by sebastian-pop** [opentap/opentap#901]
**Environment:**

Windows 7, 64-bit

Test Automation 9.19.0-rc.1 (reproduced on 9.18.4)

**Steps to reproduce:**

1. Start up package manager with the default repo `https://packages.opentap.io`
2. Packages are not listed
3. Go to settings
4. Edit default repo to `http://packages.opentap.io`
Packages are now listed

**Actual result:**

* **https**://packages.opentap.io doesn't work
* **http**://packages.opentap.io works

[PackageManager_2022-10-21_02-35-39.txt](https://github.com/opentap/opentap/files/9899856/PackageManager_2022-10-21_02-35-39.txt)

![image](https://user-images.githubusercontent.com/97734470/198977204-5cce83a1-c89f-4df5-af45-d322ee0ef4eb.png)

**Expected result:**

On Windows 10 both work

`tap package list` only works with  **http**

**Other remarks:**

**Comment by alnlarsen** [comment]
Let's figure out what can be done to add the missing certificates on Windows 7

**Comment by alnlarsen** [comment]
Let's improve the error message. Let's find out if we can detect a missing certificate from the exception.

**Comment by alnlarsen** [comment]
.NET uses Internet Explorer cyphers to secure https calls in Windows 7. IE11 does not support any of the cyphers installed server-side: that's why the secure SSL/TLS channel could not be created.

I was able to reproduce the problem by trying to make https requests in powershell (by directly using the same HttpClient like OpenTAP). I was not able to find a workaround to the problem. Here's what I tried: 

1. Trying all possible combinations of C# ServicePointManager properties (as suggested in 90% of StackOverflow answers relating to this problem) (I created a powershell script for this test that I ran after each attempt in this listing)
2. Fully update Windows 7, including optional patches suggested in various StackOverflow answers
3. Applying additional TLS settings in the registry (https://support.microsoft.com/en-us/topic/update-to-enable-tls-1-1-and-tls-1-2-as-default-secure-protocols-in-winhttp-in-windows-c4bd73d2-31d7-761e-0178-11268bb10392#bkmk_easy)
4. Updating .NET Framework to 4.8
5. Hacking OpenTAP to use .NET 6 instead of .NET Framework
6. Manually updating the list of supported cyphers in some Windows group policy settings (https://learn.microsoft.com/en-us/windows/win32/secauthn/tls-cipher-suites-in-windows-7)
7. Installing Microsoft Edge
8. Installing Webview2
9. Installing Visual Studio + asp.net SDK to check if any development dependencies included a workaround

I was able to make https requests using curl.exe and Chrome, so it would theoretically be possible to continue supporting windows 7 by creating our own HttpClient implementation build on e.g. libcurl, but I don't think this is worth the effort.

**Comment by Denrask** [comment]
We won't specifically add more support for Windows 7.
